////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MIDTFillGraph_CTEC                                                         //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
//                                                                            //
// This task contains the following graphs :                                  //
//    MyGraph_CTEC                                                            //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MIDTFillGraph_CTECGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTFillGraph_CTEC.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"


ClassImp(MIDTFillGraph_CTEC)

//______________________________________________________________________________
void MIDTFillGraph_CTEC::Init()
{
}

//______________________________________________________________________________
void MIDTFillGraph_CTEC::BeginOfRun()
{
}

//______________________________________________________________________________
void MIDTFillGraph_CTEC::Event()
{
}

//______________________________________________________________________________
void MIDTFillGraph_CTEC::EndOfRun()
{
}

//______________________________________________________________________________
void MIDTFillGraph_CTEC::Terminate()
{
}

