///////////////////////////////////////////////////////////////////////////////
//                                                                           //
// MIDTFillGraph                                                             //
//                                                                           //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                           //
//                                                                           //
// Please note: The following information is only correct after executing    //
// the ROMEBuilder.                                                          //
//                                                                           //
// This task accesses the following folders :                                //
//     ODB                                                                   //
//                                                                           //
// This task contains the following graphs :                                 //
//    MyGraph                                                                //
//                                                                           //
// The histograms/graph are created and saved automaticaly by the task.      //
//                                                                           //
// The following method can be used to get a handle of the histogram/graph : //
//                                                                           //
// Get<Histogram/Graph Name>()                                               //
//                                                                           //
// For histogram/graph arrays use :                                          //
//                                                                           //
// Get<Histogram/Graph Name>At(Int_t index)                                  //
//                                                                           //
//                                                                           //
///////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                       */
#include "generated/MIDTFillGraphGeneratedIncludes.h"

///////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the       *
 * following line will be lost next time ROMEBuilder is executed.            */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTFillGraph.h"
#include "ROMEiostream.h"
#include "TStyle.h"
#include "TROOT.h"
#include "TFile.h"
#include "TPad.h"
#include "TGraph.h"
#include <TTree.h>
#include "ROMEODBOfflineDataBase.h"
#include "MIDODB.h"
#include <TBranch.h>

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"

int   evID = 0.;
int   tStamp = 0;
int tilt[3];

static TFile *fTreeFile = NULL;
static TTree *fEventTree = NULL;

ClassImp(MIDTFillGraph)

//_____________________________________________________________________________
void MIDTFillGraph::Init()
{
}

//_____________________________________________________________________________
void MIDTFillGraph::BeginOfRun()
{
   TString treeFile = "data-out/tilt_tree_run";
   treeFile += Form("%05i",gAnalyzer->GetODB()->GetRunNumber());
   treeFile += ".root";

   fTreeFile = TFile::Open(treeFile.Data(), "RECREATE");   
   fTreeFile->cd();
   fEventTree = new TTree("g2tilt","TILT SENSOR DATA");
   fEventTree->SetAutoSave(300000000); // autosave when 300 Mbyte written.
   fEventTree->SetMaxVirtualSize(300000000); // 300 Mbyte

   // Set branches.
   fEventTree->Branch("Timestamp",&tStamp,"Timestamp/I");
   fEventTree->Branch("Tilt0",&tilt[0],"Tilt0/I");
   fEventTree->Branch("Tilt1",&tilt[1],"Tilt1/I");
   fEventTree->Branch("Tilt2",&tilt[2],"Tilt2/I");
}


//_____________________________________________________________________________
void MIDTFillGraph::Event()
{
  if (IsMyGraphActive()) {
    
    tStamp = gAnalyzer->GetActiveDAQ()->GetTimeStamp();

    int N = gAnalyzer->GetMidasDAQ()->GetTILTBankEntries();
      
    for (int i = 0; i < N; ++i) {
      tilt[i] = gAnalyzer->GetMidasDAQ()->GetTILTBankAt(i);
    }

    if (gAnalyzer->GetMidasDAQ()->GetTILTBankEntries() > 0) {
      fEventTree->Fill();
    }
  }
}

//_____________________________________________________________________________
void MIDTFillGraph::EndOfRun()
{
  fTreeFile->cd();
  fTreeFile->Write();
  fTreeFile->Close();
}

//______________________________________________________________________________
void MIDTFillGraph::Terminate()
{
}

