////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MIDTFillGraph                                                              //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     ODB                                                                    //
//                                                                            //
// This task contains the following graphs :                                  //
//    MyGraph                                                                 //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MIDTFillGraphGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTFillGraph.h"
#include "ROMEiostream.h"
#include "TStyle.h"
#include "TROOT.h"
#include "TFile.h"
#include "TPad.h"
#include "TGraph.h"
#include <TTree.h>
#include "ROMEODBOfflineDataBase.h"
#include "MIDODB.h"
#include <TBranch.h>
#include "shim_structs.hh"

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"

int   evID = 0.;
gm2::mscb_cart_t mscb;
TFile *fTreeFile = NULL;
TTree *fEventTree = NULL;

ClassImp(MIDTFillGraph)

//______________________________________________________________________________
void MIDTFillGraph::Init()
{
}

//______________________________________________________________________________
void MIDTFillGraph::BeginOfRun()
{
   TString treeFile = "data-out/mscb_cart_tree_";
   treeFile += Form("%05i",gAnalyzer->GetODB()->GetRunNumber());
   treeFile += ".root";

   fTreeFile = TFile::Open(treeFile.Data(), "RECREATE");   
   fTreeFile->cd();

   fEventTree = new TTree("t_mscb_cart","Slow Control Data From Shim Cart");
   fEventTree->Branch("cart", &mscb.midas_time, gm2::mscb_cart_str);
}

//______________________________________________________________________________
void MIDTFillGraph::Event()
{
  if (IsMyGraphActive()) {
	  
    //tree stuff
    mscb.midas_time = gAnalyzer->GetActiveDAQ()->GetTimeStamp();

    if (gAnalyzer->GetMidasDAQ()->GetINPTBankEntries() > 0) {

      for (int i = 0; i < 8; ++i) {
        mscb.temp[i] = gAnalyzer->GetMidasDAQ()->GetINPTBankAt(i);
      }

      for (int i = 0; i < 4; ++i) {
        mscb.ctec[i] = gAnalyzer->GetMidasDAQ()->GetINPTBankAt(i + 8);
      }

      fEventTree->Fill();
    }
  }
}

//______________________________________________________________________________
void MIDTFillGraph::EndOfRun()
{
  fTreeFile->cd();
  fTreeFile->Write();
  fTreeFile->Close();
}

//______________________________________________________________________________
void MIDTFillGraph::Terminate()
{
}

