////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MIDTFillGraph                                                              //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     ODB                                                                    //
//                                                                            //
// This task contains the following graphs :                                  //
//    MyGraph                                                                 //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MIDTFillGraphGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTFillGraph.h"
#include "ROMEiostream.h"
#include "TStyle.h"
#include "TROOT.h"
#include "TFile.h"
#include "TPad.h"
#include "TGraph.h"
#include <TTree.h>
#include "ROMEODBOfflineDataBase.h"
#include "MIDODB.h"
#include <TBranch.h>

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"

int   evID = 0.;
int   tStamp = 0;
float temp[8];
float capac[4];

static TFile *fTreeFile = NULL;
static TTree *fEventTree = NULL;

ClassImp(MIDTFillGraph)

//______________________________________________________________________________
void MIDTFillGraph::Init()
{
}

//______________________________________________________________________________
void MIDTFillGraph::BeginOfRun()
{
   TString treeFile = "data-out/sc_tree_run";
   treeFile += Form("%05i",gAnalyzer->GetODB()->GetRunNumber());
   treeFile += ".root";

   fTreeFile = TFile::Open(treeFile.Data(), "RECREATE");   
   fTreeFile->cd();
   fEventTree = new TTree("g2slow","SLOW CONTROL DATA");
   fEventTree->SetAutoSave(300000000); // autosave when 300 Mbyte written.
   fEventTree->SetMaxVirtualSize(300000000); // 300 Mbyte

   //set branches.  should generalize to use var like nTempChan, nCapacChan, etc.
   fEventTree->Branch("Timestamp",&tStamp,"Timestamp/I");
   fEventTree->Branch("Temp0",&temp[0],"Temp0/F");
   fEventTree->Branch("Temp1",&temp[1],"Temp1/F");
   fEventTree->Branch("Temp2",&temp[2],"Temp2/F");
   fEventTree->Branch("Temp3",&temp[3],"Temp3/F");
   fEventTree->Branch("Temp4",&temp[4],"Temp4/F");
   fEventTree->Branch("Temp5",&temp[5],"Temp5/F");
   fEventTree->Branch("Temp6",&temp[6],"Temp6/F");
   fEventTree->Branch("Temp7",&temp[7],"Temp7/F");
   fEventTree->Branch("Capac0",&capac[0],"Capac0/F");
   fEventTree->Branch("Capac1",&capac[1],"Capac1/F");
   fEventTree->Branch("Capac2",&capac[2],"Capac2/F");
   fEventTree->Branch("Capac3",&capac[3],"Capac3/F");
}

//______________________________________________________________________________
void MIDTFillGraph::Event()
{
  if (IsMyGraphActive()) {
	  
    //tree stuff
    tStamp = gAnalyzer->GetActiveDAQ()->GetTimeStamp();
    
    int N = gAnalyzer->GetMidasDAQ()->GetINPTBankEntries();

    for (Int_t i = 0; i < N; i++) {

      if (i < 8) {
        temp[i] = gAnalyzer->GetMidasDAQ()->GetINPTBankAt(i);
      } else {
        capac[i-8] = gAnalyzer->GetMidasDAQ()->GetINPTBankAt(i);
      }
    }

    if (gAnalyzer->GetMidasDAQ()->GetINPTBankEntries() > 0) {
      fEventTree->Fill();
    }
  }
}

//______________________________________________________________________________
void MIDTFillGraph::EndOfRun()
{
  fTreeFile->cd();
  fTreeFile->Write();
  fTreeFile->Close();
}

//______________________________________________________________________________
void MIDTFillGraph::Terminate()
{
}

