/********************************************************************
* DataLibraryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataLibraryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataLibraryDict();
extern void G__cpp_setup_inheritanceDataLibraryDict();
extern void G__cpp_setup_typetableDataLibraryDict();
extern void G__cpp_setup_memvarDataLibraryDict();
extern void G__cpp_setup_globalDataLibraryDict();
extern void G__cpp_setup_memfuncDataLibraryDict();
extern void G__cpp_setup_funcDataLibraryDict();
extern void G__set_cpp_environmentDataLibraryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTemps.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataLibraryDictLN_TClass;
extern G__linked_taginfo G__DataLibraryDictLN_TBuffer;
extern G__linked_taginfo G__DataLibraryDictLN_TMemberInspector;
extern G__linked_taginfo G__DataLibraryDictLN_TObject;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_TTemps;

/* STUB derived class for protected member access */
